version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql-codel-container
    environment:
      MYSQL_ROOT_PASSWORD: devrootpass
      MYSQL_DATABASE: qsdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-codel-container
    ports:
      - "5000:5000" 
    volumes:
      - .:/app

volumes:
  db_data: