version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql-codel-container
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-codel-container
    ports:
      - "80:5000" 
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FWT_TOKEN: ${FWT_TOKEN}
      MYSQL_HOST: ${MYSQL_HOST}  # Ensure that the backend knows where the DB is
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db  # Ensures backend waits for db service to start before running

  nginx:
    container_name: fproxy-codel-container
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

volumes:
  db_data: