version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql-codel-container
    environment:
      MYSQL_ROOT_PASSWORD: devrootpass
      MYSQL_DATABASE: qsdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-codel-container
    ports:
      - "5000:5000" 
    volumes:
      - .:/app
    env_file:
      - .env  # This loads the variables from the .env file
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      MYSQL_HOST: db  # Ensure that the backend knows where the DB is
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_DATABASE: qsdb
    depends_on:
      - db  # Ensures backend waits for db service to start before running

volumes:
  db_data: